In [1]:
import numpy as np
import matplotlib.pyplot as plt

**Convolution Mathematical Definition:**

$$\text{Output}[i,j] = \sum_m \sum_n \text{Input}[i+m, j+n] \times \text{Filter}[m,n]$$

In [ ]:
def manual_convolution(image, kernel):
    img_height, img_width = image.shape
    kernel_height, kernel_width = kernel.shape
    
    # output size
    output_height = img_height - kernel_height + 1
    output_width = img_width - kernel_width + 1
    
    output = np.zeros((output_height, output_width))
    
    for i in range(output_height):
        for j in range(output_width):
            region = image[i:i+kernel_height, j:j+kernel_width]
            output[i, j] = np.sum(region * kernel)
    
    return output

In [5]:
image = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

kernel = np.array([[-1, 0, 1],
                   [-2, 0, 2],
                   [-1, 0, 1]])

result = manual_convolution(image, kernel)

print("Original Image:")
print(image)
print("\nKernel:")
print(kernel)
print("\nConvolved Output:")
print(result)

Original Image:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Kernel:
[[-1  0  1]
 [-2  0  2]
 [-1  0  1]]

Convolved Output:
[[8. 8.]
 [8. 8.]]
